### ISSUE TITLE
RSS Match question

### ISSUE THREAD

**Issue by DarkSir23** [philborman/LazyLibrarian#13]
I've got 5 or so RSS feeds.  I'm searching for a book that I know matches.  I can see it match in the line

`03-Apr-2017 12:00:52 - DEBUG   :: SEARCHRSS : RSS Author/Title Match: 100/100 for XXXXXXXXXXX`

However, after finishing the search, it returns this:
`03-Apr-2017 12:00:53 - DEBUG   :: SEARCHRSS : Nearest RSS match (75%): XXXXXXXXXX <extra keywords from the feed>
03-Apr-2017 12:00:53 - DEBUG   :: SEARCHRSS : Searches returned no results. Adding book XXXXXXXXXX to queue.
03-Apr-2017 12:00:53 - INFO    :: SEARCHRSS : RSS Search for Wanted items complete, found 0 books
`

So I'm guessing what happens is the match is falling under the threshhold, despite containing an exact match.  Is there a way to weight a match like that higher (where the title of the book is matched at the beginning of the RSS entry, so that perhaps it would discount extra keywords in the RSS title)?

Hope that makes sense.  I'll happily clarify, if need be.

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

**Comment by philborman** [comment]
The first line matches 100/100 meaning all words in the authorname and all
words in the bookname are present.
This gets downgraded, losing a point for each unwanted word, I'm guessing
there must be a lot of them?  The excess words are dropping it down to  a
75% match.  The reasoning behind downgrading for extra words is to try and
stop single book titles matching against omnibus editions when you don't
want them to.  Maybe the downgrading is too harsh, could drop a percentage
point for every 2 words or 3 words instead of every word?  Maybe you could
drop your match %  in config?  Maybe we could have a different % for rss if
they produce more excess words?  Maybe we could ignore certain words that
only occur in rss results ?  Not sure how to proceed. What are the extra
words, anything easily removable?

**Comment by DarkSir23** [comment]
Not easily removable.   The provider adds all the torrent keywords such as politics, united states, buddhism at the end of the RSS title.  Is the match % only modifiable in the config file?  I didn't see it in the web interface.  

I don't know if there's a good solution, but I can certainly try changing the match percentage, and go from there.  I've just noticed a lot fewer matches against my RSS feeds than one would expect :)

**Comment by philborman** [comment]
The match percentage is in config processing tab, Search Match Ratio

Any characters between the title and the keywords we can split on, 
title:keywords or title (keywords) ?

We could weight the matching words being nearer the front, but that 
won't help (for example) with omnibus versions where you might get 
title1,title2,title3 as a box set and you just want title1

**Comment by DarkSir23** [comment]
Yeah, the keywords are in the RSS Title as [keyword, keyword, key phrase, etc]

Interesting side note, magazines with short names tend to snag a lot of false matches.  Many all at once.  Especially now that I've gone from an 85% match rate to a 75% match rate.

**Comment by philborman** [comment]
Ok so we can ignore everything after the [  in the scoring system and push
the match value back up to 85 or 90 or higher.
I will add that into tonights new version.

Anything with short names will be a problem with getting exact matches, but
the date matching will help eliminating non magazines.

**Comment by DarkSir23** [comment]
Yeah, it's just pulling anything with Magazine in the name :)  I'm just gonna drop it, as I think it's a defunct magazine anyway.
