### ISSUE TITLE
Not an issue:  Author Update

### ISSUE THREAD

**Issue by DarkSir23** [philborman/LazyLibrarian#6]
I didn't see it in Pending Jobs, so I'm not sure how often it happens.  How often does LL refresh authors to get new book releases?

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

**Comment by philborman** [comment]
It doesn't automatically, you need to run RefreshActiveAuthors on the
Authors page, or  forceActiveAuthorsUpdate  in the api.  I did wonder about
automating it, but how often should we check?

Scanning the whole author list can take quite a while, and authors aren't
that quick writing books. We cache author/book results, and expire them
after x days ( cache expiry set in config )  so needs to be at least as
long as that.

Maybe use that as a base figure and check after twice that long? What do
you think...

On Wed, 25 Jan 2017 at 20:52 DarkSir23 <notifications@github.com> wrote:

I didn't see it in Pending Jobs, so I'm not sure how often it happens. How
often does LL refresh authors to get new book releases?

To help with identifying and fixing issues, please include as much
information as possible, including:
LazyLibrarian version number (at the bottom of config page) Operating
system used (windows, mac, linux, NAS type) Interface in use (default,
bookstrap) Source of your LazyLibrarian installation (git, zip file, 3rd
party package) Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines
just before the error occurs can give useful context and greatly assist
with debugging.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/philborman/LazyLibrarian/issues/6>, or mute the thread

**Comment by DarkSir23** [comment]
I think anytime you automatically refresh authors, it could be bad, if you have a lot of authors.  I would:

Hourly, check the author table for the author with the oldest update timestamp.  If that timestamp is older than the threshhold, update that author.  That way you don't hammer goodreads and get temporarily banned from them (That happened several times while I was importing my library)

**Comment by DarkSir23** [comment]
Then threshhold could be 30 days, 10 days, whatever.

**Comment by philborman** [comment]
Good idea.
Just added code to do that. Check once per hour for oldest author, if over
cache age, refresh.

Will run it overnight to make sure it works as expected.

**Comment by philborman** [comment]
Well, seems ok. I've just changed it to take account of the number of active authors, so we now do ( cache_expiry_time div number_of_authors ) and update the oldest author. Should refresh every author then inside the cache limit. Also set a minimum interval of 10 minutes in case you have loads of authors and a very short cache expiry.   Will push to DobyTang in a few hours, just pondering what to do if maths says run < 10 mins, 1.refresh all authors, 2.exit and leave for manual refresh, 3.accept not all will be done inside the cache expiry.  At the moment I think  option 3.

**Comment by DarkSir23** [comment]
Awesome!  I've been running it since a bit before midnight.  It looks like it's doing exactly what I was hoping for.

**Comment by DarkSir23** [comment]
Hmm, since I updated this morning, author update no longer shows up in the job list.

**Comment by philborman** [comment]
Have you got cache_age set in config?  We use that to calculate time
intervals for the background task. If it's zero we don't run (same as the
other tasks)

**Comment by DarkSir23** [comment]
I also can't restart or shutdown from the interface.  So I killed it and restarted, got this:

File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/LazyLibrarian.py", line 226, in <module>
    main()
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/LazyLibrarian.py", line 206, in main
    lazylibrarian.start()
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/__init__.py", line 1558, in start
    restartJobs(start='Start')
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/common.py", line 204, in restartJobs
    scheduleJob(start, 'search_rss_book')
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/common.py", line 145, in scheduleJob
    logger.debug("%s %s job in %s minutes" % (action, target. lazylibrarian.SEARCHRSS_INTERVAL))
AttributeError: 'str' object has no attribute 'lazylibrarian'

**Comment by philborman** [comment]
Yes, just updating. That period should be a comma.  Not sure why 
restart/shutdown aren't working though...

**Comment by DarkSir23** [comment]
Hehe, I found it too.  I fix ed that, and it fixed restarts as well.  I'm guessing it wasn't parsing the rest of common.py properly?

**Comment by DarkSir23** [comment]
This looks to be working well.
